### ISSUE TITLE
Please document how to set the system profile

### ISSUE THREAD

**Issue by centic9** [Dynatrace/Dynatrace-IntelliJ-IDEA-Integration-Plugin#1]
I was trying to set the plugin up according to the instructions in the README, but then discovered that I also need to set the system profile as part of the run-configuration for unit-tests. Please add that in the description.

Additionally I did not find a setting where I can specify the system profile for normal applications (not unit tests) as there is no "AppMon" tab in the Run-Configuration settings?

**Comment by maciekmm** [comment]
Thanks for reporting the issue, I've enabled the AppMon executor for all Java configurations.

Regarding the documentation:
A simple screenshot showing where the configuration is located is already there: https://github.com/Dynatrace/Dynatrace-IntelliJ-IDEA-Integration-Plugin#run-configurations

The default system profile is Monitoring, if someone uses a different one, one should be aware of a need to change it. Would you have any suggestion on where (which part of readme) to put the aforementioned information?

Thanks

**Comment by centic9** [comment]
Ok, you are right, I was doing a text-search for "profile", so it did not find the screenshot :)
