### ISSUE TITLE
Running with Dynatrace Agent is not actually injecting the agent

### ISSUE THREAD

**Issue by centic9** [Dynatrace/Dynatrace-IntelliJ-IDEA-Integration-Plugin#2]
I have set up the integration as far as it is documented. When I start a unit test with Dynatrace integration, the eventlog states that it starts a new test-run, but no Agent-Log-output is visible in the normal console and no agent connection is visible in Dynatrace AppMon. 

Is there any way I can investigate why this happens?

See screenshots:

![visitflow - c__workspaces_visitflow - visitflow_test - _testsrc_demo_escl_2016-08-12_13-31-37](https://cloud.githubusercontent.com/assets/548322/17621135/b45d3b92-6091-11e6-8120-9a8519b098a7.png)
![settings_2016-08-12_13-31-53](https://cloud.githubusercontent.com/assets/548322/17621136/b4608fcc-6091-11e6-879a-d841287a1879.png)
![run_debug configurations_2016-08-12_13-32-08](https://cloud.githubusercontent.com/assets/548322/17621134/b45c9a70-6091-11e6-8f9a-c6110d2ff1b7.png)

**Comment by maciekmm** [comment]
@centic9 
In the console log, click on the grayed out execution command "C:..." and check if an agent path is present there.

**Comment by centic9** [comment]
Sorry, my bad, I also had Dynatrace OneAgent installed and it disables Dynatrace AppMon Agent silently.
