### ISSUE TITLE
Intellij Using wrong port when collector configured to use non standard port

### ISSUE THREAD

**Issue by themankudz** [Dynatrace/Dynatrace-IntelliJ-IDEA-Integration-Plugin#7]
![dt appmon local](https://user-images.githubusercontent.com/4438924/29359734-b729f62c-8277-11e7-83ff-2f16c1907871.PNG)
[dt_IntelliJ_22220.0.txt](https://github.com/Dynatrace/Dynatrace-AppMon-IntelliJ-IDEA-Integration-Plugin/files/1227930/dt_IntelliJ_22220.0.txt)

I'm trying to integrate dynatrace with intellij but I keep getting errors.

I have something else running on the machine that is using port 9998 so I changed the configuration to point to the collector on port 9997 after changing the server configuration. I've attached a screenshot of my configuration as well as the startup log for my run configuration.

Within the log it shows this:

Trying to connect to Collector for up to 30000 seconds
2017-08-16 11:08:05 [000000e4] info    [native] Connected to Collector localhost:9998

even though the connection settings are set to use port 9997

2017-08-16 11:08:07 [0000022c] info    [native] Agent library ............... c:/program files/dynatrace/dynatrace 7.0/agent/lib64/dtagentcore.dll
2017-08-16 11:08:07 [0000022c] info    [native] Options string .............. wait=30000,name=IntelliJ,server=localhost,port=9997

**Comment by dglugla** [comment]
@themankudz could you please verify if the new release (2.0.5) solved that issue?

**Comment by themankudz** [comment]
@dglugla I can confirm that it's working as expected now. Thanks!
